project_id = "mdrbioxjnqjjdgnhzwfh"

[functions.defi-chat]
verify_jwt = false

[functions.generate-infographic]
verify_jwt = false

[functions.review-contribution]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false